#!/usr/bin/ruby -I../worker/tests/ -I./worker/tests/ -I../../worker/tests/ -I../worker/ -I../../worker/ -I./worker/ -I./parser/ -I../parser/
#
#  This is a simple wrapper that will run the complete test-suite.
#
# Steve
# -- 
#



require 'test/unit'
require 'fileutils'



#
# Find where this file is located.
#
dir = File.dirname(__FILE__)

#
# Load each file in the same directory.
#
Dir.glob(File.join(dir,"t*.rb")).each do |test|
  require test
end

